### ISSUE TITLE
JumpVaders are picky with where you stand

### ISSUE THREAD

**Issue by TheMasterBlaster** [VenomCodeDev/JumpVaderMod#3]
JumpVaders want you to stand dead center (or really close to it) when using them to move up, causing problems with moving you. Even with blocks on either side it does it.

**Comment by AuxAtlas** [comment]
These are both bugs, and I'll look into them asap. Should be a simple fix for both, but im currently away from home for a day or two.
Could you split this into two issues if possible? I prefer a dedicated issue for each bug. Thanks!!

**Comment by AuxAtlas** [comment]
If you could let me know what minecraft version and(if you know how) what mod version youre using that would be helpful in advance. I switched from a internal SNEAK event to ServerAPI's SNEAK event in recent JumpVader versions.

**Comment by TheMasterBlaster** [comment]
The MC Version is 1.20.1, and the mod version is 1.0.3.

**Comment by AuxAtlas** [comment]
Attempted to fix this with latest commit 2bccfd9 . This would be [JumpVaderMod v1.0.8+mc1.20.1](https://modrinth.com/mod/jumpvader/version/1.0.8+1.20.1). There seems to be some weird interaction with the way I was teleporting the player. Im doing it the "traditional" way now so hopefully itll work. Let me know if the issue persists and thanks for reporting it to me!

**Comment by TheMasterBlaster** [comment]
Using build #12: Commit [2bccfd9] / version 1.0.8. Seems like nothing has really changed. The issue is exactly the same from my testing.

**Comment by AuxAtlas** [comment]
Fixed and tested working in [v1.0.9+mc1.20.1](https://modrinth.com/mod/jumpvader/version/1.0.9+1.20.1). Thank you for reporting and let me know if you have any further issues!

**Comment by TheMasterBlaster** [comment]
I have installed v1.0.9 and I'm still having issues with warping up using a JumpVader if I'm not near center, it seems warping down does not have the same requirements though.

**Comment by AuxAtlas** [comment]
> I have installed v1.0.9 and I'm still having issues with warping up using a JumpVader if I'm not near center, it seems warping down does not have the same requirements though.

Sorry, I didnt see this. So im not really able to replicate the issue on my end. Would it be possible for you to post a image of how you have the jump vaders setup as well as the blocks around them? I think I understand what you're saying but I just want to be sure. Also, please remove the .jar file for ServerAPI from your mods folder now if its still there, as that one should be referenced in JumpVadersv1.0.9  . Im sure its not what's causing this issue, but im trying to rule out other possible problems. Thanks!

EDIT: Are you in singleplayer by chance? Ive done all of the testing for this mod on a dedicated multiplayer server so that could possibly be an issue if so.
